services:
  postgres:
    image: postgres:16
    container_name: aplicometro-db
    environment:
      POSTGRES_DB: aplicometro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aplicometro-net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  aplicometro-api:
    build:
      context: .
    container_name: aplicometro-api
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aplicometro-net

volumes:
  pgdata:

networks:
  aplicometro-net:
