spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/aplicometro
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1h em milissegundos

logging:
  level:
    root: INFO

server:
  port: ${PORT:8080}
