configs:
  environment: LOCAL

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aplicometro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE