-- Drop the existing user_role table if it exists
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  description TEXT
);

-- Insert initial roles into the roles table
INSERT INTO roles (name, description) VALUES
  ('USER', 'Default user role with basic permissions'),
  ('ADMIN', 'Administrator with full permissions');