name: Coverage Badge

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests and generate coverage
        run: ./mvnw clean verify

      - name: Extract coverage from XML and generate badge
        run: |
          mkdir -p .github/badges
          COVERAGE=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" target/site/jacoco/jacoco.xml)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" target/site/jacoco/jacoco.xml)
          TOTAL=$(($COVERAGE + $MISSED))
          PERCENT=$(echo "scale=2; 100 * $COVERAGE / $TOTAL" | bc)

          COLOR=red
          if (( $(echo "$PERCENT > 90" | bc -l) )); then COLOR=brightgreen
          elif (( $(echo "$PERCENT > 70" | bc -l) )); then COLOR=yellow
          fi

          echo "Gerando badge de cobertura: $PERCENT%"
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='130' height='20'>
            <linearGradient id='b' x2='0' y2='100%%'>
              <stop offset='0' stop-color='#bbb' stop-opacity='.1'/>
              <stop offset='1' stop-opacity='.1'/>
            </linearGradient>
            <rect rx='3' width='130' height='20' fill='#555'/>
            <rect rx='3' x='80' width='50' height='20' fill='$COLOR'/>
            <path fill='$COLOR' d='M80 0h4v20h-4z'/>
            <rect rx='3' width='130' height='20' fill='url(#b)'/>
            <g fill='#fff' text-anchor='middle' font-family='Verdana' font-size='11'>
              <text x='40' y='15'>coverage</text>
              <text x='105' y='15'>${PERCENT}%</text>
            </g>
          </svg>" > .github/badges/coverage.svg

      - name: Commit badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .github/badges/coverage.svg
          git commit -m "chore: update test coverage badge [skip ci]" || echo "No changes"
          git push
