name: Build, Test and Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run tests and check coverage
        run: ./mvnw verify

      - name: Check JaCoCo coverage threshold
        run: |
          COVERAGE=$(grep -A 1 '<counter type="INSTRUCTION">' target/site/jacoco/jacoco.xml | grep covered | sed -E 's/.*covered="([0-9]+)".*/\1/')
          MISSED=$(grep -A 1 '<counter type="INSTRUCTION">' target/site/jacoco/jacoco.xml | grep missed | sed -E 's/.*missed="([0-9]+)".*/\1/')
          TOTAL=$((COVERAGE + MISSED))
          PERCENT=$((100 * COVERAGE / TOTAL))
          echo "Coverage: $PERCENT%"
          if [ $PERCENT -lt 80 ]; then
            echo "❌ Cobertura abaixo de 80%. Falhando o build."
            exit 1
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Deploy to Render
        run: echo "🚀 Aqui você pode colocar lógica de deploy (Webhook, CLI etc)"
